/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import library.Book;
import library.LibraryManagementSystem;
import library.Student;

/**
 *
 * @author Abdo Nagy
 */
public class Borrow_Book extends javax.swing.JFrame {
    ArrayList<Student> ListStudents= new ArrayList<Student>();
    ArrayList<Book> ListBooks= new ArrayList<Book>();
    LibraryManagementSystem P= LibraryManagementSystem.getInstance();
    /**
     * Creates new form Borrow_Book
     */
    public Borrow_Book() {
        initComponents();
        try{
           ListStudents= P.getAllStudents();
           for(int i=0;i<ListStudents.size();i++){
            StudentsName.addItem(ListStudents.get(i).getName());
        
        }
        }catch(Exception s){
            JOptionPane.showMessageDialog(this,s.getMessage());
        }
        try{
           ListBooks= P.getAvailableBooks();
           for(int i=0;i<ListBooks.size();i++){
            BorrowedBooksName.addItem(ListBooks.get(i).getTitle());
        
        }
        }catch(Exception n){
            JOptionPane.showMessageDialog(this,n.getMessage());
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Students = new javax.swing.JLabel();
        BorrowBookInterface = new javax.swing.JLabel();
        StudentsName = new javax.swing.JComboBox<>();
        BorrowedBooks = new javax.swing.JLabel();
        BorrowedBooksName = new javax.swing.JComboBox<>();
        BorrowBook = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Students.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        Students.setText("Student Name");

        BorrowBookInterface.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        BorrowBookInterface.setText("          Borrow Books");

        StudentsName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                StudentsNameComponentShown(evt);
            }
        });

        BorrowedBooks.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        BorrowedBooks.setText("Borrowed Book");

        BorrowedBooksName.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                BorrowedBooksNameComponentAdded(evt);
            }
        });
        BorrowedBooksName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BorrowedBooksNameComponentShown(evt);
            }
        });
        BorrowedBooksName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowedBooksNameActionPerformed(evt);
            }
        });

        BorrowBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-borrow-book-48.png"))); // NOI18N
        BorrowBook.setText("Borrow");
        BorrowBook.setBorder(null);
        BorrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBookActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-close-window-48.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrowedBooks)
                    .addComponent(BorrowedBooksName, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Students)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(BorrowBookInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(Exit)
                        .addContainerGap())
                    .addComponent(StudentsName, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(BorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BorrowBookInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Exit))
                .addGap(92, 92, 92)
                .addComponent(Students)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BorrowedBooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BorrowedBooksName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(BorrowBook)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        dispose();
        BookManag D=new BookManag();
        D.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void BorrowedBooksNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowedBooksNameActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrowedBooksNameActionPerformed

    private void BorrowedBooksNameComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_BorrowedBooksNameComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrowedBooksNameComponentAdded

    private void StudentsNameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_StudentsNameComponentShown
         // TODO add your handling code here:
    }//GEN-LAST:event_StudentsNameComponentShown

    private void BorrowedBooksNameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BorrowedBooksNameComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrowedBooksNameComponentShown

    private void BorrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBookActionPerformed
        try{
            int[]arr= new int[20];
            int[]arr1= new int[20];
            for(int i=0;i<ListStudents.size();i++){
                arr[i]= P.getAllStudents().get(i).getUnvId();}
            int SelectedValue=StudentsName.getSelectedIndex();
            int z=arr[SelectedValue];
            
            for(int j=0;j<ListBooks.size();j++){
                arr1[j]= P.getAvailableBooks().get(j).getId();}
            int SelectedValue1=BorrowedBooksName.getSelectedIndex();
            int x=arr1[SelectedValue1];
            P.borrowBook(z, x);
            dispose();
            BookManag S=new BookManag();
            S.show();
            
        }catch(Exception v){
            JOptionPane.showMessageDialog(this,v.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrowBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrow_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrow_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrow_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrow_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrow_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrowBook;
    private javax.swing.JLabel BorrowBookInterface;
    private javax.swing.JLabel BorrowedBooks;
    private javax.swing.JComboBox<String> BorrowedBooksName;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Students;
    private javax.swing.JComboBox<String> StudentsName;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
